//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int Id { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Wechat { get; set; }
        public string QQ { get; set; }
        public string Site { get; set; }
        public string Fax { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
    }
}
