//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class theSiteDBEF : DbContext
    {
        public theSiteDBEF()
            : base("name=theSiteDBEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<ContactInfo> ContactInfoes { get; set; }

        public System.Data.Entity.DbSet<theSite.Models.Article> Articles { get; set; }
    }
}
